# Usa una imagen base ligera de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requerimientos y lo instala
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia el resto del código (incluyendo notificaciones.py)
COPY . .

# Expone el puerto 8501 (por defecto Streamlit usa este puerto)
EXPOSE 8501

# Comando para iniciar la aplicación Streamlit
CMD ["streamlit", "run", "notificaciones.py", "--server.port=8501", "--server.enableCORS=false"]
