# Usa una imagen base de Python
FROM python:3.10-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY requirements.txt requirements.txt
COPY notificaciones.py .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto 8501 (Streamlit)
EXPOSE 8501

# Comando para ejecutar Streamlit
CMD ["streamlit", "run", "notificaciones.py", "--server.port=8501", "--server.address=0.0.0.0"]
